server:
  port: 8567

spring:
  main:
    banner-mode: off

app:
  notification:
    channels: TG

rss:
  update:
    cron: ${RSS_UPDATE_CRON:0 * * * * *} # (second) (minute) (hour) (day of the month) (month) (day of the week)
  process:
    cron: ${RSS_PROCESS_CRON:10 * * * * *} # (second) (minute) (hour) (day of the month) (month) (day of the week)