server:
  port: 8567
  http2:
    enabled: true
  compression:
    enabled: true

springdoc:
  swagger-ui:
    url: /rest-api-spec.yaml
    use-root-path: true
    disable-swagger-default-url: true

spring:
  main:
    banner-mode: off


app:
  notification:
    channels: TG
    telegram:
      username: ${BOT_USERNAME}
      token: ${BOT_TOKEN}
      chats: ${TG_CHATS}

# (second) (minute) (hour) (day of the month) (month) (day of the week)
rss:
  create:
    cron: ${RSS_UPDATE_CRON:*/5 * * * * *}
  update:
    cron: ${RSS_UPDATE_CRON:*/20 * * * * *}
  process:
    cron: ${RSS_PROCESS_CRON:*/10 * * * * *}
  events:
    send:
      cron: ${RSS_SEND_CRON:*/10 * * * * *}

log:
  service:
    name: RssWebApi