@startuml

skinparam componentStyle rectangle

component [client] #Yellow

component Processor {
    component [API] as api #LightBlue
    component [Processor] as pr #LightGreen
    component [Storage] as store #LightCoral
    component [Requester] as request
    component [Notifier] as notify #LightGreen
}

component Internet as internet

client -r-> api : HTTP request\nwith auth
api -> pr : Validate and\nsend to process
pr -> request
request -r-> internet
internet -l-> request : Get rss\ndata
request -> pr
pr -d-> notify : Notify via\nTelegram, Slack\netc.
pr -u-> store : In memory\nor db storage

@enduml