@startuml

skinparam componentStyle rectangle

component [client] #Yellow

component Processor {
    component [Web] as web #LightBlue
    component [Storage] as store #LightCoral
    component [Requester] as request
    component [Notifier] as notify #LightGreen
}

component Internet as internet

client -r-> web : HTTP request\nwith auth
web -> request
request -r-> internet
internet -l-> request : Get rss\ndata
request -> web
web -d-> notify : Notify via\nTelegram, Slack\netc.
web -u-> store : In memory\nor db storage

@enduml